# Generated by Django 5.2 on 2025-05-02 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('profile_picture', models.ImageField(upload_to='profiles/', verbose_name='الصورة الشخصية')),
                ('bio', models.TextField(verbose_name='نبذة تعريفية')),
                ('role', models.CharField(choices=[('president', 'رئيس المجلس'), ('vice_president', 'نائب الرئيس'), ('academic_agent', 'الوكيل الأكاديمي'), ('admin_agent', 'الوكيل الإداري'), ('department_head', 'رئيس قسم'), ('department_member', 'عضو قسم'), ('active_member', 'عضو نشط'), ('regular_member', 'عضو منتسب')], max_length=30, verbose_name='الصفة')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم (إن وجد)')),
                ('serial_number', models.CharField(max_length=10, unique=True, verbose_name='الرقم التسلسلي')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='رمز QR')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانضمام')),
                ('is_active', models.BooleanField(default=True, verbose_name='العضوية مفعّلة')),
                ('show_public_profile', models.BooleanField(default=True, verbose_name='إظهار الملف للعامة')),
            ],
        ),
    ]
