# Generated by Django 5.2 on 2025-05-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='member',
            name='qr_code_image',
        ),
        migrations.RemoveField(
            model_name='member',
            name='show_public_profile',
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('president', 'رئيس المجلس'), ('vice_president', 'نائب الرئيس'), ('academic_dean', 'الوكيل الأكاديمي'), ('admin_dean', 'الوكيل الإداري'), ('department_head', 'رئيس قسم'), ('department_member', 'عضو قسم'), ('active_member', 'عضو نشط'), ('affiliate_member', 'عضو منتسب')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
