# Generated by Django 5.2 on 2025-05-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_bio_remove_member_qr_code_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('president', 'رئيس المجلس'), ('vice_president', 'نائب الرئيس'), ('academic_agent', 'الوكيل الأكاديمي'), ('admin_agent', 'الوكيل الإداري'), ('department_head', 'رئيس قسم'), ('department_member', 'عضو قسم'), ('active_member', 'عضو نشط'), ('regular_member', 'عضو منتسب')], max_length=50),
        ),
    ]
