# Generated by Django 5.2 on 2025-05-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_qr_code_image_alter_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('president', 'رئيس المجلس'), ('vice_president', 'نائب الرئيس'), ('academic_dean', 'الوكيل الأكاديمي'), ('admin_dean', 'الوكيل الإداري'), ('department_head', 'رئيس قسم'), ('department_member', 'عضو قسم'), ('active_member', 'عضو نشط'), ('affiliate_member', 'عضو منتسب')], max_length=50),
        ),
    ]
