# Generated by Django 5.2 on 2025-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_profile_url_alter_member_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='show_public_profile',
            field=models.BooleanField(default=True),
        ),
    ]
